// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AuthenticationRequest;
@class AuthenticationRequest_Builder;
@class AuthenticationResponse;
@class AuthenticationResponse_Builder;
@class BlockContactRequest;
@class BlockContactRequest_Builder;
@class BlockContactResponse;
@class BlockContactResponse_Builder;
@class ChangeContactDetailRequest;
@class ChangeContactDetailRequest_Builder;
@class ChangeContactDetailResponse;
@class ChangeContactDetailResponse_Builder;
@class ChangePasswordRequest;
@class ChangePasswordRequest_Builder;
@class ChangePasswordResponse;
@class ChangePasswordResponse_Builder;
@class ChangeProfileRequest;
@class ChangeProfileRequest_Builder;
@class ChangeProfileResponse;
@class ChangeProfileResponse_Builder;
@class Contact;
@class ContactDetailRequest;
@class ContactDetailRequest_Builder;
@class ContactDetailResponse;
@class ContactDetailResponse_Builder;
@class ContactRequest;
@class ContactRequest_Builder;
@class ContactResponse;
@class ContactResponse_Builder;
@class Contact_Builder;
@class Message;
@class MessageList;
@class MessageList_Builder;
@class MessageRequest;
@class MessageRequest_Builder;
@class MessageResponse;
@class MessageResponse_Builder;
@class Message_Builder;
@class Profile;
@class ProfileRequest;
@class ProfileRequest_Builder;
@class ProfileResponse;
@class ProfileResponse_Builder;
@class Profile_Builder;
@class RegisterRequest;
@class RegisterRequest_Builder;
@class RegisterResponse;
@class RegisterResponse_Builder;
@class SendMessageRequest;
@class SendMessageRequest_Builder;
@class SendMessageResponse;
@class SendMessageResponse_Builder;
@class UnAuthenticationRequest;
@class UnAuthenticationRequest_Builder;
@class UnAuthenticationResponse;
@class UnAuthenticationResponse_Builder;
@class ValidateCodeRequest;
@class ValidateCodeRequest_Builder;
@class ValidateCodeResponse;
@class ValidateCodeResponse_Builder;
typedef enum {
  AuthenticationResponse_ErrorCodeTypeInvalidUserName = 1,
  AuthenticationResponse_ErrorCodeTypeInvalidPassword = 2,
  AuthenticationResponse_ErrorCodeTypeInvalidPasswordExceedCount = 3,
  AuthenticationResponse_ErrorCodeTypeNotActivate = 4,
  AuthenticationResponse_ErrorCodeTypeSucceed = 5,
} AuthenticationResponse_ErrorCodeType;

BOOL AuthenticationResponse_ErrorCodeTypeIsValidValue(AuthenticationResponse_ErrorCodeType value);

typedef enum {
  Contact_ContactSourceTypeOrderFrom = 1,
  Contact_ContactSourceTypeOrderTo = 2,
  Contact_ContactSourceTypeSubscribeFrom = 4,
  Contact_ContactSourceTypeSubscribeTo = 8,
} Contact_ContactSourceType;

BOOL Contact_ContactSourceTypeIsValidValue(Contact_ContactSourceType value);


@interface ModelsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface AuthenticationRequest : PBGeneratedMessage {
@private
  BOOL hasUserName_:1;
  BOOL hasPassword_:1;
  NSString* userName;
  NSString* password;
}
- (BOOL) hasUserName;
- (BOOL) hasPassword;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* password;

+ (AuthenticationRequest*) defaultInstance;
- (AuthenticationRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthenticationRequest_Builder*) builder;
+ (AuthenticationRequest_Builder*) builder;
+ (AuthenticationRequest_Builder*) builderWithPrototype:(AuthenticationRequest*) prototype;

+ (AuthenticationRequest*) parseFromData:(NSData*) data;
+ (AuthenticationRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthenticationRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AuthenticationRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthenticationRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthenticationRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthenticationRequest_Builder : PBGeneratedMessage_Builder {
@private
  AuthenticationRequest* result;
}

- (AuthenticationRequest*) defaultInstance;

- (AuthenticationRequest_Builder*) clear;
- (AuthenticationRequest_Builder*) clone;

- (AuthenticationRequest*) build;
- (AuthenticationRequest*) buildPartial;

- (AuthenticationRequest_Builder*) mergeFrom:(AuthenticationRequest*) other;
- (AuthenticationRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthenticationRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserName;
- (NSString*) userName;
- (AuthenticationRequest_Builder*) setUserName:(NSString*) value;
- (AuthenticationRequest_Builder*) clearUserName;

- (BOOL) hasPassword;
- (NSString*) password;
- (AuthenticationRequest_Builder*) setPassword:(NSString*) value;
- (AuthenticationRequest_Builder*) clearPassword;
@end

@interface AuthenticationResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasUserId_:1;
  BOOL hasPasswordFailCount_:1;
  BOOL hasToken_:1;
  BOOL hasErrorCode_:1;
  BOOL isSucceed_:1;
  int32_t userId;
  int32_t passwordFailCount;
  NSString* token;
  AuthenticationResponse_ErrorCodeType errorCode;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasUserId;
- (BOOL) hasToken;
- (BOOL) hasPasswordFailCount;
- (BOOL) hasErrorCode;
- (BOOL) isSucceed;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t passwordFailCount;
@property (readonly) AuthenticationResponse_ErrorCodeType errorCode;

+ (AuthenticationResponse*) defaultInstance;
- (AuthenticationResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthenticationResponse_Builder*) builder;
+ (AuthenticationResponse_Builder*) builder;
+ (AuthenticationResponse_Builder*) builderWithPrototype:(AuthenticationResponse*) prototype;

+ (AuthenticationResponse*) parseFromData:(NSData*) data;
+ (AuthenticationResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthenticationResponse*) parseFromInputStream:(NSInputStream*) input;
+ (AuthenticationResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthenticationResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthenticationResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthenticationResponse_Builder : PBGeneratedMessage_Builder {
@private
  AuthenticationResponse* result;
}

- (AuthenticationResponse*) defaultInstance;

- (AuthenticationResponse_Builder*) clear;
- (AuthenticationResponse_Builder*) clone;

- (AuthenticationResponse*) build;
- (AuthenticationResponse*) buildPartial;

- (AuthenticationResponse_Builder*) mergeFrom:(AuthenticationResponse*) other;
- (AuthenticationResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthenticationResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (AuthenticationResponse_Builder*) setIsSucceed:(BOOL) value;
- (AuthenticationResponse_Builder*) clearIsSucceed;

- (BOOL) hasUserId;
- (int32_t) userId;
- (AuthenticationResponse_Builder*) setUserId:(int32_t) value;
- (AuthenticationResponse_Builder*) clearUserId;

- (BOOL) hasToken;
- (NSString*) token;
- (AuthenticationResponse_Builder*) setToken:(NSString*) value;
- (AuthenticationResponse_Builder*) clearToken;

- (BOOL) hasPasswordFailCount;
- (int32_t) passwordFailCount;
- (AuthenticationResponse_Builder*) setPasswordFailCount:(int32_t) value;
- (AuthenticationResponse_Builder*) clearPasswordFailCount;

- (BOOL) hasErrorCode;
- (AuthenticationResponse_ErrorCodeType) errorCode;
- (AuthenticationResponse_Builder*) setErrorCode:(AuthenticationResponse_ErrorCodeType) value;
- (AuthenticationResponse_Builder*) clearErrorCode;
@end

@interface UnAuthenticationRequest : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  int32_t userId;
  NSString* token;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;

+ (UnAuthenticationRequest*) defaultInstance;
- (UnAuthenticationRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UnAuthenticationRequest_Builder*) builder;
+ (UnAuthenticationRequest_Builder*) builder;
+ (UnAuthenticationRequest_Builder*) builderWithPrototype:(UnAuthenticationRequest*) prototype;

+ (UnAuthenticationRequest*) parseFromData:(NSData*) data;
+ (UnAuthenticationRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnAuthenticationRequest*) parseFromInputStream:(NSInputStream*) input;
+ (UnAuthenticationRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnAuthenticationRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UnAuthenticationRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UnAuthenticationRequest_Builder : PBGeneratedMessage_Builder {
@private
  UnAuthenticationRequest* result;
}

- (UnAuthenticationRequest*) defaultInstance;

- (UnAuthenticationRequest_Builder*) clear;
- (UnAuthenticationRequest_Builder*) clone;

- (UnAuthenticationRequest*) build;
- (UnAuthenticationRequest*) buildPartial;

- (UnAuthenticationRequest_Builder*) mergeFrom:(UnAuthenticationRequest*) other;
- (UnAuthenticationRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UnAuthenticationRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (UnAuthenticationRequest_Builder*) setToken:(NSString*) value;
- (UnAuthenticationRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (UnAuthenticationRequest_Builder*) setUserId:(int32_t) value;
- (UnAuthenticationRequest_Builder*) clearUserId;
@end

@interface UnAuthenticationResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasUserId_:1;
  BOOL isSucceed_:1;
  int32_t userId;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasUserId;
- (BOOL) isSucceed;
@property (readonly) int32_t userId;

+ (UnAuthenticationResponse*) defaultInstance;
- (UnAuthenticationResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UnAuthenticationResponse_Builder*) builder;
+ (UnAuthenticationResponse_Builder*) builder;
+ (UnAuthenticationResponse_Builder*) builderWithPrototype:(UnAuthenticationResponse*) prototype;

+ (UnAuthenticationResponse*) parseFromData:(NSData*) data;
+ (UnAuthenticationResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnAuthenticationResponse*) parseFromInputStream:(NSInputStream*) input;
+ (UnAuthenticationResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnAuthenticationResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UnAuthenticationResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UnAuthenticationResponse_Builder : PBGeneratedMessage_Builder {
@private
  UnAuthenticationResponse* result;
}

- (UnAuthenticationResponse*) defaultInstance;

- (UnAuthenticationResponse_Builder*) clear;
- (UnAuthenticationResponse_Builder*) clone;

- (UnAuthenticationResponse*) build;
- (UnAuthenticationResponse*) buildPartial;

- (UnAuthenticationResponse_Builder*) mergeFrom:(UnAuthenticationResponse*) other;
- (UnAuthenticationResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UnAuthenticationResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (UnAuthenticationResponse_Builder*) setIsSucceed:(BOOL) value;
- (UnAuthenticationResponse_Builder*) clearIsSucceed;

- (BOOL) hasUserId;
- (int32_t) userId;
- (UnAuthenticationResponse_Builder*) setUserId:(int32_t) value;
- (UnAuthenticationResponse_Builder*) clearUserId;
@end

@interface Contact : PBGeneratedMessage {
@private
  BOOL hasIsBlocked_:1;
  BOOL hasIsProvider_:1;
  BOOL hasContactId_:1;
  BOOL hasGender_:1;
  BOOL hasSource_:1;
  BOOL hasName_:1;
  BOOL hasCustomName_:1;
  BOOL hasPinyin_:1;
  BOOL hasLastContactTime_:1;
  BOOL hasTileUrl_:1;
  BOOL hasLisence_:1;
  BOOL hasPublishClassType_:1;
  BOOL hasSignature_:1;
  BOOL isBlocked_:1;
  BOOL isProvider_:1;
  int32_t contactId;
  int32_t gender;
  int32_t source;
  NSString* name;
  NSString* customName;
  NSString* pinyin;
  NSString* lastContactTime;
  NSString* tileUrl;
  NSString* lisence;
  NSString* publishClassType;
  NSString* signature;
}
- (BOOL) hasContactId;
- (BOOL) hasName;
- (BOOL) hasCustomName;
- (BOOL) hasPinyin;
- (BOOL) hasIsBlocked;
- (BOOL) hasLastContactTime;
- (BOOL) hasGender;
- (BOOL) hasSource;
- (BOOL) hasTileUrl;
- (BOOL) hasIsProvider;
- (BOOL) hasLisence;
- (BOOL) hasPublishClassType;
- (BOOL) hasSignature;
@property (readonly) int32_t contactId;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* customName;
@property (readonly, retain) NSString* pinyin;
- (BOOL) isBlocked;
@property (readonly, retain) NSString* lastContactTime;
@property (readonly) int32_t gender;
@property (readonly) int32_t source;
@property (readonly, retain) NSString* tileUrl;
- (BOOL) isProvider;
@property (readonly, retain) NSString* lisence;
@property (readonly, retain) NSString* publishClassType;
@property (readonly, retain) NSString* signature;

+ (Contact*) defaultInstance;
- (Contact*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Contact_Builder*) builder;
+ (Contact_Builder*) builder;
+ (Contact_Builder*) builderWithPrototype:(Contact*) prototype;

+ (Contact*) parseFromData:(NSData*) data;
+ (Contact*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Contact*) parseFromInputStream:(NSInputStream*) input;
+ (Contact*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Contact*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Contact*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Contact_Builder : PBGeneratedMessage_Builder {
@private
  Contact* result;
}

- (Contact*) defaultInstance;

- (Contact_Builder*) clear;
- (Contact_Builder*) clone;

- (Contact*) build;
- (Contact*) buildPartial;

- (Contact_Builder*) mergeFrom:(Contact*) other;
- (Contact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Contact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasContactId;
- (int32_t) contactId;
- (Contact_Builder*) setContactId:(int32_t) value;
- (Contact_Builder*) clearContactId;

- (BOOL) hasName;
- (NSString*) name;
- (Contact_Builder*) setName:(NSString*) value;
- (Contact_Builder*) clearName;

- (BOOL) hasCustomName;
- (NSString*) customName;
- (Contact_Builder*) setCustomName:(NSString*) value;
- (Contact_Builder*) clearCustomName;

- (BOOL) hasPinyin;
- (NSString*) pinyin;
- (Contact_Builder*) setPinyin:(NSString*) value;
- (Contact_Builder*) clearPinyin;

- (BOOL) hasIsBlocked;
- (BOOL) isBlocked;
- (Contact_Builder*) setIsBlocked:(BOOL) value;
- (Contact_Builder*) clearIsBlocked;

- (BOOL) hasLastContactTime;
- (NSString*) lastContactTime;
- (Contact_Builder*) setLastContactTime:(NSString*) value;
- (Contact_Builder*) clearLastContactTime;

- (BOOL) hasGender;
- (int32_t) gender;
- (Contact_Builder*) setGender:(int32_t) value;
- (Contact_Builder*) clearGender;

- (BOOL) hasSource;
- (int32_t) source;
- (Contact_Builder*) setSource:(int32_t) value;
- (Contact_Builder*) clearSource;

- (BOOL) hasTileUrl;
- (NSString*) tileUrl;
- (Contact_Builder*) setTileUrl:(NSString*) value;
- (Contact_Builder*) clearTileUrl;

- (BOOL) hasIsProvider;
- (BOOL) isProvider;
- (Contact_Builder*) setIsProvider:(BOOL) value;
- (Contact_Builder*) clearIsProvider;

- (BOOL) hasLisence;
- (NSString*) lisence;
- (Contact_Builder*) setLisence:(NSString*) value;
- (Contact_Builder*) clearLisence;

- (BOOL) hasPublishClassType;
- (NSString*) publishClassType;
- (Contact_Builder*) setPublishClassType:(NSString*) value;
- (Contact_Builder*) clearPublishClassType;

- (BOOL) hasSignature;
- (NSString*) signature;
- (Contact_Builder*) setSignature:(NSString*) value;
- (Contact_Builder*) clearSignature;
@end

@interface ContactRequest : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  BOOL hasTimeStamp_:1;
  int32_t userId;
  NSString* token;
  NSString* timeStamp;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
- (BOOL) hasTimeStamp;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* timeStamp;

+ (ContactRequest*) defaultInstance;
- (ContactRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactRequest_Builder*) builder;
+ (ContactRequest_Builder*) builder;
+ (ContactRequest_Builder*) builderWithPrototype:(ContactRequest*) prototype;

+ (ContactRequest*) parseFromData:(NSData*) data;
+ (ContactRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ContactRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactRequest_Builder : PBGeneratedMessage_Builder {
@private
  ContactRequest* result;
}

- (ContactRequest*) defaultInstance;

- (ContactRequest_Builder*) clear;
- (ContactRequest_Builder*) clone;

- (ContactRequest*) build;
- (ContactRequest*) buildPartial;

- (ContactRequest_Builder*) mergeFrom:(ContactRequest*) other;
- (ContactRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (ContactRequest_Builder*) setToken:(NSString*) value;
- (ContactRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (ContactRequest_Builder*) setUserId:(int32_t) value;
- (ContactRequest_Builder*) clearUserId;

- (BOOL) hasTimeStamp;
- (NSString*) timeStamp;
- (ContactRequest_Builder*) setTimeStamp:(NSString*) value;
- (ContactRequest_Builder*) clearTimeStamp;
@end

@interface ContactResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasTimeStamp_:1;
  BOOL isSucceed_:1;
  NSString* timeStamp;
  NSMutableArray* mutableContactsList;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasTimeStamp;
- (BOOL) isSucceed;
@property (readonly, retain) NSString* timeStamp;
- (NSArray*) contactsList;
- (Contact*) contactsAtIndex:(int32_t) index;

+ (ContactResponse*) defaultInstance;
- (ContactResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactResponse_Builder*) builder;
+ (ContactResponse_Builder*) builder;
+ (ContactResponse_Builder*) builderWithPrototype:(ContactResponse*) prototype;

+ (ContactResponse*) parseFromData:(NSData*) data;
+ (ContactResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ContactResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactResponse_Builder : PBGeneratedMessage_Builder {
@private
  ContactResponse* result;
}

- (ContactResponse*) defaultInstance;

- (ContactResponse_Builder*) clear;
- (ContactResponse_Builder*) clone;

- (ContactResponse*) build;
- (ContactResponse*) buildPartial;

- (ContactResponse_Builder*) mergeFrom:(ContactResponse*) other;
- (ContactResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (ContactResponse_Builder*) setIsSucceed:(BOOL) value;
- (ContactResponse_Builder*) clearIsSucceed;

- (NSArray*) contactsList;
- (Contact*) contactsAtIndex:(int32_t) index;
- (ContactResponse_Builder*) replaceContactsAtIndex:(int32_t) index with:(Contact*) value;
- (ContactResponse_Builder*) addContacts:(Contact*) value;
- (ContactResponse_Builder*) addAllContacts:(NSArray*) values;
- (ContactResponse_Builder*) clearContactsList;

- (BOOL) hasTimeStamp;
- (NSString*) timeStamp;
- (ContactResponse_Builder*) setTimeStamp:(NSString*) value;
- (ContactResponse_Builder*) clearTimeStamp;
@end

@interface BlockContactRequest : PBGeneratedMessage {
@private
  BOOL hasIsBlocked_:1;
  BOOL hasUserId_:1;
  BOOL hasContactId_:1;
  BOOL hasToken_:1;
  BOOL isBlocked_:1;
  int32_t userId;
  int32_t contactId;
  NSString* token;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
- (BOOL) hasContactId;
- (BOOL) hasIsBlocked;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;
@property (readonly) int32_t contactId;
- (BOOL) isBlocked;

+ (BlockContactRequest*) defaultInstance;
- (BlockContactRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BlockContactRequest_Builder*) builder;
+ (BlockContactRequest_Builder*) builder;
+ (BlockContactRequest_Builder*) builderWithPrototype:(BlockContactRequest*) prototype;

+ (BlockContactRequest*) parseFromData:(NSData*) data;
+ (BlockContactRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BlockContactRequest*) parseFromInputStream:(NSInputStream*) input;
+ (BlockContactRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BlockContactRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BlockContactRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BlockContactRequest_Builder : PBGeneratedMessage_Builder {
@private
  BlockContactRequest* result;
}

- (BlockContactRequest*) defaultInstance;

- (BlockContactRequest_Builder*) clear;
- (BlockContactRequest_Builder*) clone;

- (BlockContactRequest*) build;
- (BlockContactRequest*) buildPartial;

- (BlockContactRequest_Builder*) mergeFrom:(BlockContactRequest*) other;
- (BlockContactRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BlockContactRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (BlockContactRequest_Builder*) setToken:(NSString*) value;
- (BlockContactRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (BlockContactRequest_Builder*) setUserId:(int32_t) value;
- (BlockContactRequest_Builder*) clearUserId;

- (BOOL) hasContactId;
- (int32_t) contactId;
- (BlockContactRequest_Builder*) setContactId:(int32_t) value;
- (BlockContactRequest_Builder*) clearContactId;

- (BOOL) hasIsBlocked;
- (BOOL) isBlocked;
- (BlockContactRequest_Builder*) setIsBlocked:(BOOL) value;
- (BlockContactRequest_Builder*) clearIsBlocked;
@end

@interface BlockContactResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasIsBlocked_:1;
  BOOL hasContactId_:1;
  BOOL isSucceed_:1;
  BOOL isBlocked_:1;
  int32_t contactId;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasContactId;
- (BOOL) hasIsBlocked;
- (BOOL) isSucceed;
@property (readonly) int32_t contactId;
- (BOOL) isBlocked;

+ (BlockContactResponse*) defaultInstance;
- (BlockContactResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BlockContactResponse_Builder*) builder;
+ (BlockContactResponse_Builder*) builder;
+ (BlockContactResponse_Builder*) builderWithPrototype:(BlockContactResponse*) prototype;

+ (BlockContactResponse*) parseFromData:(NSData*) data;
+ (BlockContactResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BlockContactResponse*) parseFromInputStream:(NSInputStream*) input;
+ (BlockContactResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BlockContactResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BlockContactResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BlockContactResponse_Builder : PBGeneratedMessage_Builder {
@private
  BlockContactResponse* result;
}

- (BlockContactResponse*) defaultInstance;

- (BlockContactResponse_Builder*) clear;
- (BlockContactResponse_Builder*) clone;

- (BlockContactResponse*) build;
- (BlockContactResponse*) buildPartial;

- (BlockContactResponse_Builder*) mergeFrom:(BlockContactResponse*) other;
- (BlockContactResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BlockContactResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (BlockContactResponse_Builder*) setIsSucceed:(BOOL) value;
- (BlockContactResponse_Builder*) clearIsSucceed;

- (BOOL) hasContactId;
- (int32_t) contactId;
- (BlockContactResponse_Builder*) setContactId:(int32_t) value;
- (BlockContactResponse_Builder*) clearContactId;

- (BOOL) hasIsBlocked;
- (BOOL) isBlocked;
- (BlockContactResponse_Builder*) setIsBlocked:(BOOL) value;
- (BlockContactResponse_Builder*) clearIsBlocked;
@end

@interface ContactDetailRequest : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasContactId_:1;
  BOOL hasToken_:1;
  int32_t userId;
  int32_t contactId;
  NSString* token;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
- (BOOL) hasContactId;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;
@property (readonly) int32_t contactId;

+ (ContactDetailRequest*) defaultInstance;
- (ContactDetailRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactDetailRequest_Builder*) builder;
+ (ContactDetailRequest_Builder*) builder;
+ (ContactDetailRequest_Builder*) builderWithPrototype:(ContactDetailRequest*) prototype;

+ (ContactDetailRequest*) parseFromData:(NSData*) data;
+ (ContactDetailRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactDetailRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ContactDetailRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactDetailRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactDetailRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactDetailRequest_Builder : PBGeneratedMessage_Builder {
@private
  ContactDetailRequest* result;
}

- (ContactDetailRequest*) defaultInstance;

- (ContactDetailRequest_Builder*) clear;
- (ContactDetailRequest_Builder*) clone;

- (ContactDetailRequest*) build;
- (ContactDetailRequest*) buildPartial;

- (ContactDetailRequest_Builder*) mergeFrom:(ContactDetailRequest*) other;
- (ContactDetailRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactDetailRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (ContactDetailRequest_Builder*) setToken:(NSString*) value;
- (ContactDetailRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (ContactDetailRequest_Builder*) setUserId:(int32_t) value;
- (ContactDetailRequest_Builder*) clearUserId;

- (BOOL) hasContactId;
- (int32_t) contactId;
- (ContactDetailRequest_Builder*) setContactId:(int32_t) value;
- (ContactDetailRequest_Builder*) clearContactId;
@end

@interface ContactDetailResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasContact_:1;
  BOOL isSucceed_:1;
  Contact* contact;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasContact;
- (BOOL) isSucceed;
@property (readonly, retain) Contact* contact;

+ (ContactDetailResponse*) defaultInstance;
- (ContactDetailResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactDetailResponse_Builder*) builder;
+ (ContactDetailResponse_Builder*) builder;
+ (ContactDetailResponse_Builder*) builderWithPrototype:(ContactDetailResponse*) prototype;

+ (ContactDetailResponse*) parseFromData:(NSData*) data;
+ (ContactDetailResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactDetailResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ContactDetailResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactDetailResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactDetailResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactDetailResponse_Builder : PBGeneratedMessage_Builder {
@private
  ContactDetailResponse* result;
}

- (ContactDetailResponse*) defaultInstance;

- (ContactDetailResponse_Builder*) clear;
- (ContactDetailResponse_Builder*) clone;

- (ContactDetailResponse*) build;
- (ContactDetailResponse*) buildPartial;

- (ContactDetailResponse_Builder*) mergeFrom:(ContactDetailResponse*) other;
- (ContactDetailResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactDetailResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (ContactDetailResponse_Builder*) setIsSucceed:(BOOL) value;
- (ContactDetailResponse_Builder*) clearIsSucceed;

- (BOOL) hasContact;
- (Contact*) contact;
- (ContactDetailResponse_Builder*) setContact:(Contact*) value;
- (ContactDetailResponse_Builder*) setContactBuilder:(Contact_Builder*) builderForValue;
- (ContactDetailResponse_Builder*) mergeContact:(Contact*) value;
- (ContactDetailResponse_Builder*) clearContact;
@end

@interface ChangeContactDetailRequest : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  BOOL hasContact_:1;
  int32_t userId;
  NSString* token;
  Contact* contact;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
- (BOOL) hasContact;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;
@property (readonly, retain) Contact* contact;

+ (ChangeContactDetailRequest*) defaultInstance;
- (ChangeContactDetailRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChangeContactDetailRequest_Builder*) builder;
+ (ChangeContactDetailRequest_Builder*) builder;
+ (ChangeContactDetailRequest_Builder*) builderWithPrototype:(ChangeContactDetailRequest*) prototype;

+ (ChangeContactDetailRequest*) parseFromData:(NSData*) data;
+ (ChangeContactDetailRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeContactDetailRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ChangeContactDetailRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeContactDetailRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChangeContactDetailRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChangeContactDetailRequest_Builder : PBGeneratedMessage_Builder {
@private
  ChangeContactDetailRequest* result;
}

- (ChangeContactDetailRequest*) defaultInstance;

- (ChangeContactDetailRequest_Builder*) clear;
- (ChangeContactDetailRequest_Builder*) clone;

- (ChangeContactDetailRequest*) build;
- (ChangeContactDetailRequest*) buildPartial;

- (ChangeContactDetailRequest_Builder*) mergeFrom:(ChangeContactDetailRequest*) other;
- (ChangeContactDetailRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChangeContactDetailRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (ChangeContactDetailRequest_Builder*) setToken:(NSString*) value;
- (ChangeContactDetailRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (ChangeContactDetailRequest_Builder*) setUserId:(int32_t) value;
- (ChangeContactDetailRequest_Builder*) clearUserId;

- (BOOL) hasContact;
- (Contact*) contact;
- (ChangeContactDetailRequest_Builder*) setContact:(Contact*) value;
- (ChangeContactDetailRequest_Builder*) setContactBuilder:(Contact_Builder*) builderForValue;
- (ChangeContactDetailRequest_Builder*) mergeContact:(Contact*) value;
- (ChangeContactDetailRequest_Builder*) clearContact;
@end

@interface ChangeContactDetailResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasContact_:1;
  BOOL isSucceed_:1;
  Contact* contact;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasContact;
- (BOOL) isSucceed;
@property (readonly, retain) Contact* contact;

+ (ChangeContactDetailResponse*) defaultInstance;
- (ChangeContactDetailResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChangeContactDetailResponse_Builder*) builder;
+ (ChangeContactDetailResponse_Builder*) builder;
+ (ChangeContactDetailResponse_Builder*) builderWithPrototype:(ChangeContactDetailResponse*) prototype;

+ (ChangeContactDetailResponse*) parseFromData:(NSData*) data;
+ (ChangeContactDetailResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeContactDetailResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ChangeContactDetailResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeContactDetailResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChangeContactDetailResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChangeContactDetailResponse_Builder : PBGeneratedMessage_Builder {
@private
  ChangeContactDetailResponse* result;
}

- (ChangeContactDetailResponse*) defaultInstance;

- (ChangeContactDetailResponse_Builder*) clear;
- (ChangeContactDetailResponse_Builder*) clone;

- (ChangeContactDetailResponse*) build;
- (ChangeContactDetailResponse*) buildPartial;

- (ChangeContactDetailResponse_Builder*) mergeFrom:(ChangeContactDetailResponse*) other;
- (ChangeContactDetailResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChangeContactDetailResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (ChangeContactDetailResponse_Builder*) setIsSucceed:(BOOL) value;
- (ChangeContactDetailResponse_Builder*) clearIsSucceed;

- (BOOL) hasContact;
- (Contact*) contact;
- (ChangeContactDetailResponse_Builder*) setContact:(Contact*) value;
- (ChangeContactDetailResponse_Builder*) setContactBuilder:(Contact_Builder*) builderForValue;
- (ChangeContactDetailResponse_Builder*) mergeContact:(Contact*) value;
- (ChangeContactDetailResponse_Builder*) clearContact;
@end

@interface Profile : PBGeneratedMessage {
@private
  BOOL hasIsProvider_:1;
  BOOL hasUserId_:1;
  BOOL hasGender_:1;
  BOOL hasName_:1;
  BOOL hasNickName_:1;
  BOOL hasTileUrl_:1;
  BOOL hasLisence_:1;
  BOOL hasPublishClassType_:1;
  BOOL hasSignature_:1;
  BOOL isProvider_:1;
  int32_t userId;
  int32_t gender;
  NSString* name;
  NSString* nickName;
  NSString* tileUrl;
  NSString* lisence;
  NSString* publishClassType;
  NSString* signature;
}
- (BOOL) hasUserId;
- (BOOL) hasName;
- (BOOL) hasNickName;
- (BOOL) hasGender;
- (BOOL) hasTileUrl;
- (BOOL) hasIsProvider;
- (BOOL) hasLisence;
- (BOOL) hasPublishClassType;
- (BOOL) hasSignature;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* nickName;
@property (readonly) int32_t gender;
@property (readonly, retain) NSString* tileUrl;
- (BOOL) isProvider;
@property (readonly, retain) NSString* lisence;
@property (readonly, retain) NSString* publishClassType;
@property (readonly, retain) NSString* signature;

+ (Profile*) defaultInstance;
- (Profile*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Profile_Builder*) builder;
+ (Profile_Builder*) builder;
+ (Profile_Builder*) builderWithPrototype:(Profile*) prototype;

+ (Profile*) parseFromData:(NSData*) data;
+ (Profile*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Profile*) parseFromInputStream:(NSInputStream*) input;
+ (Profile*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Profile*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Profile*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Profile_Builder : PBGeneratedMessage_Builder {
@private
  Profile* result;
}

- (Profile*) defaultInstance;

- (Profile_Builder*) clear;
- (Profile_Builder*) clone;

- (Profile*) build;
- (Profile*) buildPartial;

- (Profile_Builder*) mergeFrom:(Profile*) other;
- (Profile_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Profile_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (Profile_Builder*) setUserId:(int32_t) value;
- (Profile_Builder*) clearUserId;

- (BOOL) hasName;
- (NSString*) name;
- (Profile_Builder*) setName:(NSString*) value;
- (Profile_Builder*) clearName;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (Profile_Builder*) setNickName:(NSString*) value;
- (Profile_Builder*) clearNickName;

- (BOOL) hasGender;
- (int32_t) gender;
- (Profile_Builder*) setGender:(int32_t) value;
- (Profile_Builder*) clearGender;

- (BOOL) hasTileUrl;
- (NSString*) tileUrl;
- (Profile_Builder*) setTileUrl:(NSString*) value;
- (Profile_Builder*) clearTileUrl;

- (BOOL) hasIsProvider;
- (BOOL) isProvider;
- (Profile_Builder*) setIsProvider:(BOOL) value;
- (Profile_Builder*) clearIsProvider;

- (BOOL) hasLisence;
- (NSString*) lisence;
- (Profile_Builder*) setLisence:(NSString*) value;
- (Profile_Builder*) clearLisence;

- (BOOL) hasPublishClassType;
- (NSString*) publishClassType;
- (Profile_Builder*) setPublishClassType:(NSString*) value;
- (Profile_Builder*) clearPublishClassType;

- (BOOL) hasSignature;
- (NSString*) signature;
- (Profile_Builder*) setSignature:(NSString*) value;
- (Profile_Builder*) clearSignature;
@end

@interface ProfileRequest : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  int32_t userId;
  NSString* token;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;

+ (ProfileRequest*) defaultInstance;
- (ProfileRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProfileRequest_Builder*) builder;
+ (ProfileRequest_Builder*) builder;
+ (ProfileRequest_Builder*) builderWithPrototype:(ProfileRequest*) prototype;

+ (ProfileRequest*) parseFromData:(NSData*) data;
+ (ProfileRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProfileRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ProfileRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProfileRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProfileRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProfileRequest_Builder : PBGeneratedMessage_Builder {
@private
  ProfileRequest* result;
}

- (ProfileRequest*) defaultInstance;

- (ProfileRequest_Builder*) clear;
- (ProfileRequest_Builder*) clone;

- (ProfileRequest*) build;
- (ProfileRequest*) buildPartial;

- (ProfileRequest_Builder*) mergeFrom:(ProfileRequest*) other;
- (ProfileRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProfileRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (ProfileRequest_Builder*) setToken:(NSString*) value;
- (ProfileRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (ProfileRequest_Builder*) setUserId:(int32_t) value;
- (ProfileRequest_Builder*) clearUserId;
@end

@interface ProfileResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasProfile_:1;
  BOOL isSucceed_:1;
  Profile* profile;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasProfile;
- (BOOL) isSucceed;
@property (readonly, retain) Profile* profile;

+ (ProfileResponse*) defaultInstance;
- (ProfileResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProfileResponse_Builder*) builder;
+ (ProfileResponse_Builder*) builder;
+ (ProfileResponse_Builder*) builderWithPrototype:(ProfileResponse*) prototype;

+ (ProfileResponse*) parseFromData:(NSData*) data;
+ (ProfileResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProfileResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ProfileResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProfileResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProfileResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProfileResponse_Builder : PBGeneratedMessage_Builder {
@private
  ProfileResponse* result;
}

- (ProfileResponse*) defaultInstance;

- (ProfileResponse_Builder*) clear;
- (ProfileResponse_Builder*) clone;

- (ProfileResponse*) build;
- (ProfileResponse*) buildPartial;

- (ProfileResponse_Builder*) mergeFrom:(ProfileResponse*) other;
- (ProfileResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProfileResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (ProfileResponse_Builder*) setIsSucceed:(BOOL) value;
- (ProfileResponse_Builder*) clearIsSucceed;

- (BOOL) hasProfile;
- (Profile*) profile;
- (ProfileResponse_Builder*) setProfile:(Profile*) value;
- (ProfileResponse_Builder*) setProfileBuilder:(Profile_Builder*) builderForValue;
- (ProfileResponse_Builder*) mergeProfile:(Profile*) value;
- (ProfileResponse_Builder*) clearProfile;
@end

@interface ChangeProfileRequest : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  BOOL hasProfile_:1;
  int32_t userId;
  NSString* token;
  Profile* profile;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
- (BOOL) hasProfile;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;
@property (readonly, retain) Profile* profile;

+ (ChangeProfileRequest*) defaultInstance;
- (ChangeProfileRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChangeProfileRequest_Builder*) builder;
+ (ChangeProfileRequest_Builder*) builder;
+ (ChangeProfileRequest_Builder*) builderWithPrototype:(ChangeProfileRequest*) prototype;

+ (ChangeProfileRequest*) parseFromData:(NSData*) data;
+ (ChangeProfileRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeProfileRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ChangeProfileRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeProfileRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChangeProfileRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChangeProfileRequest_Builder : PBGeneratedMessage_Builder {
@private
  ChangeProfileRequest* result;
}

- (ChangeProfileRequest*) defaultInstance;

- (ChangeProfileRequest_Builder*) clear;
- (ChangeProfileRequest_Builder*) clone;

- (ChangeProfileRequest*) build;
- (ChangeProfileRequest*) buildPartial;

- (ChangeProfileRequest_Builder*) mergeFrom:(ChangeProfileRequest*) other;
- (ChangeProfileRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChangeProfileRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (ChangeProfileRequest_Builder*) setToken:(NSString*) value;
- (ChangeProfileRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (ChangeProfileRequest_Builder*) setUserId:(int32_t) value;
- (ChangeProfileRequest_Builder*) clearUserId;

- (BOOL) hasProfile;
- (Profile*) profile;
- (ChangeProfileRequest_Builder*) setProfile:(Profile*) value;
- (ChangeProfileRequest_Builder*) setProfileBuilder:(Profile_Builder*) builderForValue;
- (ChangeProfileRequest_Builder*) mergeProfile:(Profile*) value;
- (ChangeProfileRequest_Builder*) clearProfile;
@end

@interface ChangeProfileResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasProfile_:1;
  BOOL isSucceed_:1;
  Profile* profile;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasProfile;
- (BOOL) isSucceed;
@property (readonly, retain) Profile* profile;

+ (ChangeProfileResponse*) defaultInstance;
- (ChangeProfileResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChangeProfileResponse_Builder*) builder;
+ (ChangeProfileResponse_Builder*) builder;
+ (ChangeProfileResponse_Builder*) builderWithPrototype:(ChangeProfileResponse*) prototype;

+ (ChangeProfileResponse*) parseFromData:(NSData*) data;
+ (ChangeProfileResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeProfileResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ChangeProfileResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangeProfileResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChangeProfileResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChangeProfileResponse_Builder : PBGeneratedMessage_Builder {
@private
  ChangeProfileResponse* result;
}

- (ChangeProfileResponse*) defaultInstance;

- (ChangeProfileResponse_Builder*) clear;
- (ChangeProfileResponse_Builder*) clone;

- (ChangeProfileResponse*) build;
- (ChangeProfileResponse*) buildPartial;

- (ChangeProfileResponse_Builder*) mergeFrom:(ChangeProfileResponse*) other;
- (ChangeProfileResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChangeProfileResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (ChangeProfileResponse_Builder*) setIsSucceed:(BOOL) value;
- (ChangeProfileResponse_Builder*) clearIsSucceed;

- (BOOL) hasProfile;
- (Profile*) profile;
- (ChangeProfileResponse_Builder*) setProfile:(Profile*) value;
- (ChangeProfileResponse_Builder*) setProfileBuilder:(Profile_Builder*) builderForValue;
- (ChangeProfileResponse_Builder*) mergeProfile:(Profile*) value;
- (ChangeProfileResponse_Builder*) clearProfile;
@end

@interface Message : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasContactId_:1;
  BOOL hasContent_:1;
  BOOL hasSendTime_:1;
  int32_t userId;
  int32_t contactId;
  NSString* content;
  NSString* sendTime;
}
- (BOOL) hasUserId;
- (BOOL) hasContactId;
- (BOOL) hasContent;
- (BOOL) hasSendTime;
@property (readonly) int32_t userId;
@property (readonly) int32_t contactId;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSString* sendTime;

+ (Message*) defaultInstance;
- (Message*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Message_Builder*) builder;
+ (Message_Builder*) builder;
+ (Message_Builder*) builderWithPrototype:(Message*) prototype;

+ (Message*) parseFromData:(NSData*) data;
+ (Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromInputStream:(NSInputStream*) input;
+ (Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Message_Builder : PBGeneratedMessage_Builder {
@private
  Message* result;
}

- (Message*) defaultInstance;

- (Message_Builder*) clear;
- (Message_Builder*) clone;

- (Message*) build;
- (Message*) buildPartial;

- (Message_Builder*) mergeFrom:(Message*) other;
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Message_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (Message_Builder*) setUserId:(int32_t) value;
- (Message_Builder*) clearUserId;

- (BOOL) hasContactId;
- (int32_t) contactId;
- (Message_Builder*) setContactId:(int32_t) value;
- (Message_Builder*) clearContactId;

- (BOOL) hasContent;
- (NSString*) content;
- (Message_Builder*) setContent:(NSString*) value;
- (Message_Builder*) clearContent;

- (BOOL) hasSendTime;
- (NSString*) sendTime;
- (Message_Builder*) setSendTime:(NSString*) value;
- (Message_Builder*) clearSendTime;
@end

@interface MessageList : PBGeneratedMessage {
@private
  BOOL hasContactId_:1;
  int32_t contactId;
  NSMutableArray* mutableMessagesList;
}
- (BOOL) hasContactId;
@property (readonly) int32_t contactId;
- (NSArray*) messagesList;
- (Message*) messagesAtIndex:(int32_t) index;

+ (MessageList*) defaultInstance;
- (MessageList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageList_Builder*) builder;
+ (MessageList_Builder*) builder;
+ (MessageList_Builder*) builderWithPrototype:(MessageList*) prototype;

+ (MessageList*) parseFromData:(NSData*) data;
+ (MessageList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageList*) parseFromInputStream:(NSInputStream*) input;
+ (MessageList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageList_Builder : PBGeneratedMessage_Builder {
@private
  MessageList* result;
}

- (MessageList*) defaultInstance;

- (MessageList_Builder*) clear;
- (MessageList_Builder*) clone;

- (MessageList*) build;
- (MessageList*) buildPartial;

- (MessageList_Builder*) mergeFrom:(MessageList*) other;
- (MessageList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasContactId;
- (int32_t) contactId;
- (MessageList_Builder*) setContactId:(int32_t) value;
- (MessageList_Builder*) clearContactId;

- (NSArray*) messagesList;
- (Message*) messagesAtIndex:(int32_t) index;
- (MessageList_Builder*) replaceMessagesAtIndex:(int32_t) index with:(Message*) value;
- (MessageList_Builder*) addMessages:(Message*) value;
- (MessageList_Builder*) addAllMessages:(NSArray*) values;
- (MessageList_Builder*) clearMessagesList;
@end

@interface MessageRequest : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  BOOL hasTimeStamp_:1;
  int32_t userId;
  NSString* token;
  NSString* timeStamp;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
- (BOOL) hasTimeStamp;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* timeStamp;

+ (MessageRequest*) defaultInstance;
- (MessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageRequest_Builder*) builder;
+ (MessageRequest_Builder*) builder;
+ (MessageRequest_Builder*) builderWithPrototype:(MessageRequest*) prototype;

+ (MessageRequest*) parseFromData:(NSData*) data;
+ (MessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (MessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  MessageRequest* result;
}

- (MessageRequest*) defaultInstance;

- (MessageRequest_Builder*) clear;
- (MessageRequest_Builder*) clone;

- (MessageRequest*) build;
- (MessageRequest*) buildPartial;

- (MessageRequest_Builder*) mergeFrom:(MessageRequest*) other;
- (MessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (MessageRequest_Builder*) setToken:(NSString*) value;
- (MessageRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (MessageRequest_Builder*) setUserId:(int32_t) value;
- (MessageRequest_Builder*) clearUserId;

- (BOOL) hasTimeStamp;
- (NSString*) timeStamp;
- (MessageRequest_Builder*) setTimeStamp:(NSString*) value;
- (MessageRequest_Builder*) clearTimeStamp;
@end

@interface MessageResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasTimeStamp_:1;
  BOOL isSucceed_:1;
  NSString* timeStamp;
  NSMutableArray* mutableMessageListsList;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasTimeStamp;
- (BOOL) isSucceed;
@property (readonly, retain) NSString* timeStamp;
- (NSArray*) messageListsList;
- (MessageList*) messageListsAtIndex:(int32_t) index;

+ (MessageResponse*) defaultInstance;
- (MessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageResponse_Builder*) builder;
+ (MessageResponse_Builder*) builder;
+ (MessageResponse_Builder*) builderWithPrototype:(MessageResponse*) prototype;

+ (MessageResponse*) parseFromData:(NSData*) data;
+ (MessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (MessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  MessageResponse* result;
}

- (MessageResponse*) defaultInstance;

- (MessageResponse_Builder*) clear;
- (MessageResponse_Builder*) clone;

- (MessageResponse*) build;
- (MessageResponse*) buildPartial;

- (MessageResponse_Builder*) mergeFrom:(MessageResponse*) other;
- (MessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (MessageResponse_Builder*) setIsSucceed:(BOOL) value;
- (MessageResponse_Builder*) clearIsSucceed;

- (NSArray*) messageListsList;
- (MessageList*) messageListsAtIndex:(int32_t) index;
- (MessageResponse_Builder*) replaceMessageListsAtIndex:(int32_t) index with:(MessageList*) value;
- (MessageResponse_Builder*) addMessageLists:(MessageList*) value;
- (MessageResponse_Builder*) addAllMessageLists:(NSArray*) values;
- (MessageResponse_Builder*) clearMessageListsList;

- (BOOL) hasTimeStamp;
- (NSString*) timeStamp;
- (MessageResponse_Builder*) setTimeStamp:(NSString*) value;
- (MessageResponse_Builder*) clearTimeStamp;
@end

@interface SendMessageRequest : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  BOOL hasMessage_:1;
  int32_t userId;
  NSString* token;
  Message* message;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
- (BOOL) hasMessage;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;
@property (readonly, retain) Message* message;

+ (SendMessageRequest*) defaultInstance;
- (SendMessageRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SendMessageRequest_Builder*) builder;
+ (SendMessageRequest_Builder*) builder;
+ (SendMessageRequest_Builder*) builderWithPrototype:(SendMessageRequest*) prototype;

+ (SendMessageRequest*) parseFromData:(NSData*) data;
+ (SendMessageRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMessageRequest*) parseFromInputStream:(NSInputStream*) input;
+ (SendMessageRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SendMessageRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SendMessageRequest_Builder : PBGeneratedMessage_Builder {
@private
  SendMessageRequest* result;
}

- (SendMessageRequest*) defaultInstance;

- (SendMessageRequest_Builder*) clear;
- (SendMessageRequest_Builder*) clone;

- (SendMessageRequest*) build;
- (SendMessageRequest*) buildPartial;

- (SendMessageRequest_Builder*) mergeFrom:(SendMessageRequest*) other;
- (SendMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SendMessageRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (SendMessageRequest_Builder*) setToken:(NSString*) value;
- (SendMessageRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (SendMessageRequest_Builder*) setUserId:(int32_t) value;
- (SendMessageRequest_Builder*) clearUserId;

- (BOOL) hasMessage;
- (Message*) message;
- (SendMessageRequest_Builder*) setMessage:(Message*) value;
- (SendMessageRequest_Builder*) setMessageBuilder:(Message_Builder*) builderForValue;
- (SendMessageRequest_Builder*) mergeMessage:(Message*) value;
- (SendMessageRequest_Builder*) clearMessage;
@end

@interface SendMessageResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasErrorCode_:1;
  BOOL isSucceed_:1;
  int32_t errorCode;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasErrorCode;
- (BOOL) isSucceed;
@property (readonly) int32_t errorCode;

+ (SendMessageResponse*) defaultInstance;
- (SendMessageResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SendMessageResponse_Builder*) builder;
+ (SendMessageResponse_Builder*) builder;
+ (SendMessageResponse_Builder*) builderWithPrototype:(SendMessageResponse*) prototype;

+ (SendMessageResponse*) parseFromData:(NSData*) data;
+ (SendMessageResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMessageResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SendMessageResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SendMessageResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SendMessageResponse_Builder : PBGeneratedMessage_Builder {
@private
  SendMessageResponse* result;
}

- (SendMessageResponse*) defaultInstance;

- (SendMessageResponse_Builder*) clear;
- (SendMessageResponse_Builder*) clone;

- (SendMessageResponse*) build;
- (SendMessageResponse*) buildPartial;

- (SendMessageResponse_Builder*) mergeFrom:(SendMessageResponse*) other;
- (SendMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SendMessageResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (SendMessageResponse_Builder*) setIsSucceed:(BOOL) value;
- (SendMessageResponse_Builder*) clearIsSucceed;

- (BOOL) hasErrorCode;
- (int32_t) errorCode;
- (SendMessageResponse_Builder*) setErrorCode:(int32_t) value;
- (SendMessageResponse_Builder*) clearErrorCode;
@end

@interface RegisterRequest : PBGeneratedMessage {
@private
  BOOL hasMobilePhoneNumber_:1;
  BOOL hasName_:1;
  BOOL hasPassword_:1;
  BOOL hasPasswordConfirm_:1;
  BOOL hasValidateCode_:1;
  NSString* mobilePhoneNumber;
  NSString* name;
  NSString* password;
  NSString* passwordConfirm;
  NSString* validateCode;
}
- (BOOL) hasMobilePhoneNumber;
- (BOOL) hasName;
- (BOOL) hasPassword;
- (BOOL) hasPasswordConfirm;
- (BOOL) hasValidateCode;
@property (readonly, retain) NSString* mobilePhoneNumber;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* password;
@property (readonly, retain) NSString* passwordConfirm;
@property (readonly, retain) NSString* validateCode;

+ (RegisterRequest*) defaultInstance;
- (RegisterRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RegisterRequest_Builder*) builder;
+ (RegisterRequest_Builder*) builder;
+ (RegisterRequest_Builder*) builderWithPrototype:(RegisterRequest*) prototype;

+ (RegisterRequest*) parseFromData:(NSData*) data;
+ (RegisterRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RegisterRequest*) parseFromInputStream:(NSInputStream*) input;
+ (RegisterRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RegisterRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RegisterRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RegisterRequest_Builder : PBGeneratedMessage_Builder {
@private
  RegisterRequest* result;
}

- (RegisterRequest*) defaultInstance;

- (RegisterRequest_Builder*) clear;
- (RegisterRequest_Builder*) clone;

- (RegisterRequest*) build;
- (RegisterRequest*) buildPartial;

- (RegisterRequest_Builder*) mergeFrom:(RegisterRequest*) other;
- (RegisterRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RegisterRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMobilePhoneNumber;
- (NSString*) mobilePhoneNumber;
- (RegisterRequest_Builder*) setMobilePhoneNumber:(NSString*) value;
- (RegisterRequest_Builder*) clearMobilePhoneNumber;

- (BOOL) hasName;
- (NSString*) name;
- (RegisterRequest_Builder*) setName:(NSString*) value;
- (RegisterRequest_Builder*) clearName;

- (BOOL) hasPassword;
- (NSString*) password;
- (RegisterRequest_Builder*) setPassword:(NSString*) value;
- (RegisterRequest_Builder*) clearPassword;

- (BOOL) hasPasswordConfirm;
- (NSString*) passwordConfirm;
- (RegisterRequest_Builder*) setPasswordConfirm:(NSString*) value;
- (RegisterRequest_Builder*) clearPasswordConfirm;

- (BOOL) hasValidateCode;
- (NSString*) validateCode;
- (RegisterRequest_Builder*) setValidateCode:(NSString*) value;
- (RegisterRequest_Builder*) clearValidateCode;
@end

@interface RegisterResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasUserId_:1;
  BOOL hasErrorCode_:1;
  BOOL isSucceed_:1;
  int32_t userId;
  int32_t errorCode;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasUserId;
- (BOOL) hasErrorCode;
- (BOOL) isSucceed;
@property (readonly) int32_t userId;
@property (readonly) int32_t errorCode;

+ (RegisterResponse*) defaultInstance;
- (RegisterResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RegisterResponse_Builder*) builder;
+ (RegisterResponse_Builder*) builder;
+ (RegisterResponse_Builder*) builderWithPrototype:(RegisterResponse*) prototype;

+ (RegisterResponse*) parseFromData:(NSData*) data;
+ (RegisterResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RegisterResponse*) parseFromInputStream:(NSInputStream*) input;
+ (RegisterResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RegisterResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RegisterResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RegisterResponse_Builder : PBGeneratedMessage_Builder {
@private
  RegisterResponse* result;
}

- (RegisterResponse*) defaultInstance;

- (RegisterResponse_Builder*) clear;
- (RegisterResponse_Builder*) clone;

- (RegisterResponse*) build;
- (RegisterResponse*) buildPartial;

- (RegisterResponse_Builder*) mergeFrom:(RegisterResponse*) other;
- (RegisterResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RegisterResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (RegisterResponse_Builder*) setIsSucceed:(BOOL) value;
- (RegisterResponse_Builder*) clearIsSucceed;

- (BOOL) hasUserId;
- (int32_t) userId;
- (RegisterResponse_Builder*) setUserId:(int32_t) value;
- (RegisterResponse_Builder*) clearUserId;

- (BOOL) hasErrorCode;
- (int32_t) errorCode;
- (RegisterResponse_Builder*) setErrorCode:(int32_t) value;
- (RegisterResponse_Builder*) clearErrorCode;
@end

@interface ChangePasswordRequest : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  BOOL hasOriginalPassword_:1;
  BOOL hasPassword_:1;
  BOOL hasPasswordConfirm_:1;
  int32_t userId;
  NSString* token;
  NSString* originalPassword;
  NSString* password;
  NSString* passwordConfirm;
}
- (BOOL) hasToken;
- (BOOL) hasUserId;
- (BOOL) hasOriginalPassword;
- (BOOL) hasPassword;
- (BOOL) hasPasswordConfirm;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* originalPassword;
@property (readonly, retain) NSString* password;
@property (readonly, retain) NSString* passwordConfirm;

+ (ChangePasswordRequest*) defaultInstance;
- (ChangePasswordRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChangePasswordRequest_Builder*) builder;
+ (ChangePasswordRequest_Builder*) builder;
+ (ChangePasswordRequest_Builder*) builderWithPrototype:(ChangePasswordRequest*) prototype;

+ (ChangePasswordRequest*) parseFromData:(NSData*) data;
+ (ChangePasswordRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangePasswordRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ChangePasswordRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangePasswordRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChangePasswordRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChangePasswordRequest_Builder : PBGeneratedMessage_Builder {
@private
  ChangePasswordRequest* result;
}

- (ChangePasswordRequest*) defaultInstance;

- (ChangePasswordRequest_Builder*) clear;
- (ChangePasswordRequest_Builder*) clone;

- (ChangePasswordRequest*) build;
- (ChangePasswordRequest*) buildPartial;

- (ChangePasswordRequest_Builder*) mergeFrom:(ChangePasswordRequest*) other;
- (ChangePasswordRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChangePasswordRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (ChangePasswordRequest_Builder*) setToken:(NSString*) value;
- (ChangePasswordRequest_Builder*) clearToken;

- (BOOL) hasUserId;
- (int32_t) userId;
- (ChangePasswordRequest_Builder*) setUserId:(int32_t) value;
- (ChangePasswordRequest_Builder*) clearUserId;

- (BOOL) hasOriginalPassword;
- (NSString*) originalPassword;
- (ChangePasswordRequest_Builder*) setOriginalPassword:(NSString*) value;
- (ChangePasswordRequest_Builder*) clearOriginalPassword;

- (BOOL) hasPassword;
- (NSString*) password;
- (ChangePasswordRequest_Builder*) setPassword:(NSString*) value;
- (ChangePasswordRequest_Builder*) clearPassword;

- (BOOL) hasPasswordConfirm;
- (NSString*) passwordConfirm;
- (ChangePasswordRequest_Builder*) setPasswordConfirm:(NSString*) value;
- (ChangePasswordRequest_Builder*) clearPasswordConfirm;
@end

@interface ChangePasswordResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasErrorCode_:1;
  BOOL isSucceed_:1;
  int32_t errorCode;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasErrorCode;
- (BOOL) isSucceed;
@property (readonly) int32_t errorCode;

+ (ChangePasswordResponse*) defaultInstance;
- (ChangePasswordResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChangePasswordResponse_Builder*) builder;
+ (ChangePasswordResponse_Builder*) builder;
+ (ChangePasswordResponse_Builder*) builderWithPrototype:(ChangePasswordResponse*) prototype;

+ (ChangePasswordResponse*) parseFromData:(NSData*) data;
+ (ChangePasswordResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangePasswordResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ChangePasswordResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChangePasswordResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChangePasswordResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChangePasswordResponse_Builder : PBGeneratedMessage_Builder {
@private
  ChangePasswordResponse* result;
}

- (ChangePasswordResponse*) defaultInstance;

- (ChangePasswordResponse_Builder*) clear;
- (ChangePasswordResponse_Builder*) clone;

- (ChangePasswordResponse*) build;
- (ChangePasswordResponse*) buildPartial;

- (ChangePasswordResponse_Builder*) mergeFrom:(ChangePasswordResponse*) other;
- (ChangePasswordResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChangePasswordResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (ChangePasswordResponse_Builder*) setIsSucceed:(BOOL) value;
- (ChangePasswordResponse_Builder*) clearIsSucceed;

- (BOOL) hasErrorCode;
- (int32_t) errorCode;
- (ChangePasswordResponse_Builder*) setErrorCode:(int32_t) value;
- (ChangePasswordResponse_Builder*) clearErrorCode;
@end

@interface ValidateCodeRequest : PBGeneratedMessage {
@private
  BOOL hasPhoneNumber_:1;
  NSString* phoneNumber;
}
- (BOOL) hasPhoneNumber;
@property (readonly, retain) NSString* phoneNumber;

+ (ValidateCodeRequest*) defaultInstance;
- (ValidateCodeRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ValidateCodeRequest_Builder*) builder;
+ (ValidateCodeRequest_Builder*) builder;
+ (ValidateCodeRequest_Builder*) builderWithPrototype:(ValidateCodeRequest*) prototype;

+ (ValidateCodeRequest*) parseFromData:(NSData*) data;
+ (ValidateCodeRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ValidateCodeRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ValidateCodeRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ValidateCodeRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ValidateCodeRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ValidateCodeRequest_Builder : PBGeneratedMessage_Builder {
@private
  ValidateCodeRequest* result;
}

- (ValidateCodeRequest*) defaultInstance;

- (ValidateCodeRequest_Builder*) clear;
- (ValidateCodeRequest_Builder*) clone;

- (ValidateCodeRequest*) build;
- (ValidateCodeRequest*) buildPartial;

- (ValidateCodeRequest_Builder*) mergeFrom:(ValidateCodeRequest*) other;
- (ValidateCodeRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ValidateCodeRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (NSString*) phoneNumber;
- (ValidateCodeRequest_Builder*) setPhoneNumber:(NSString*) value;
- (ValidateCodeRequest_Builder*) clearPhoneNumber;
@end

@interface ValidateCodeResponse : PBGeneratedMessage {
@private
  BOOL hasIsSucceed_:1;
  BOOL hasErrorCode_:1;
  BOOL hasValidateCode_:1;
  BOOL isSucceed_:1;
  int32_t errorCode;
  NSString* validateCode;
}
- (BOOL) hasIsSucceed;
- (BOOL) hasErrorCode;
- (BOOL) hasValidateCode;
- (BOOL) isSucceed;
@property (readonly) int32_t errorCode;
@property (readonly, retain) NSString* validateCode;

+ (ValidateCodeResponse*) defaultInstance;
- (ValidateCodeResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ValidateCodeResponse_Builder*) builder;
+ (ValidateCodeResponse_Builder*) builder;
+ (ValidateCodeResponse_Builder*) builderWithPrototype:(ValidateCodeResponse*) prototype;

+ (ValidateCodeResponse*) parseFromData:(NSData*) data;
+ (ValidateCodeResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ValidateCodeResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ValidateCodeResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ValidateCodeResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ValidateCodeResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ValidateCodeResponse_Builder : PBGeneratedMessage_Builder {
@private
  ValidateCodeResponse* result;
}

- (ValidateCodeResponse*) defaultInstance;

- (ValidateCodeResponse_Builder*) clear;
- (ValidateCodeResponse_Builder*) clone;

- (ValidateCodeResponse*) build;
- (ValidateCodeResponse*) buildPartial;

- (ValidateCodeResponse_Builder*) mergeFrom:(ValidateCodeResponse*) other;
- (ValidateCodeResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ValidateCodeResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsSucceed;
- (BOOL) isSucceed;
- (ValidateCodeResponse_Builder*) setIsSucceed:(BOOL) value;
- (ValidateCodeResponse_Builder*) clearIsSucceed;

- (BOOL) hasErrorCode;
- (int32_t) errorCode;
- (ValidateCodeResponse_Builder*) setErrorCode:(int32_t) value;
- (ValidateCodeResponse_Builder*) clearErrorCode;

- (BOOL) hasValidateCode;
- (NSString*) validateCode;
- (ValidateCodeResponse_Builder*) setValidateCode:(NSString*) value;
- (ValidateCodeResponse_Builder*) clearValidateCode;
@end

